parameters:
    request_parameter_handler.class: EscapeHither\CrudManagerBundle\Services\RequestParameterHandler
    list_request_handler.class: EscapeHither\CrudManagerBundle\Services\ListRequestHandler
    single_resource_request_handler.class: EscapeHither\CrudManagerBundle\Services\SingleResourceRequestHandler
    new_resource_creation_handler.class: EscapeHither\CrudManagerBundle\Services\NewResourceCreationHandler
    form_factory_handler.class: EscapeHither\CrudManagerBundle\Services\FormFactoryHandler
    crud_event_dispatcher.class: EscapeHither\CrudManagerBundle\Services\CrudEventDispatcher
    flash_message_manager.class: EscapeHither\CrudManagerBundle\Services\FlashMessageManager
    resource_voter.class: EscapeHither\CrudManagerBundle\Security\ResourceVoter
    api_exeption_subscriber.class: EscapeHither\CrudManagerBundle\EventListener\ApiExceptionSubscriber



services:
    starter_kit.resource_voter:
            class: "%resource_voter.class%"
            arguments: ["@security.access.decision_manager","@request_parameter_handler"]
            public: false
            tags:
                - { name: security.voter }
            # small performance boost

    request_parameter_handler:
        class: "%request_parameter_handler.class%"
        arguments: ["@request_stack","@service_container"]
        #scope: request
    list_request_handler:
            class: "%list_request_handler.class%"
            arguments: ["@request_parameter_handler","@doctrine.orm.entity_manager"]
    single_resource_request_handler:
                class: "%single_resource_request_handler.class%"
                arguments: ["@request_parameter_handler","@doctrine.orm.entity_manager"]
    new_resource_creation_handler:
                class: "%new_resource_creation_handler.class%"
                arguments: ["@request_parameter_handler","@doctrine.orm.entity_manager"]
    form_factory_handler:
                    class: "%form_factory_handler.class%"
                    arguments: ["@request_parameter_handler","@doctrine.orm.entity_manager","@form.factory"]
    crud_event_dispatcher:
                        class: "%crud_event_dispatcher.class%"
                        arguments: ["@request_parameter_handler","@event_dispatcher"]
    flash_message_manager:
                            class: "%flash_message_manager.class%"
                            arguments: ["@request_parameter_handler"]
    api_exception_subscriber:
            class: "%api_exeption_subscriber.class%"
            arguments: ['%kernel.debug%']
            tags:
                - { name: kernel.event_subscriber }